### ISSUE TITLE
The database in the project cannot be connected. Can you provide the SQL file

### ISSUE THREAD

**Issue by zjlx** [vaalenin/chromium_fake_fingerprint#1]
The project is very cool. 
The database in the project cannot be connected. Can you provide the SQL file? 
Thank you very much.

**Comment by vaalenin** [comment]
this database was created only for remote access by customer

**Comment by zjlx** [comment]
May you just provide one format template data
Thanks a lot.

**Comment by vaalenin** [comment]
you can look into this one: https://github.com/fingerprintjs/fingerprintjs

**Comment by zjlx** [comment]
Oh, I see
Thanks!
